name: Notification on push

on:
  push:
    branches:
    - master
    - main # ‚úäüèø

env:
  CI: true
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  HUSKY_SKIP_INSTALL: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Check syntax
      run: |
        yarn install --frozen-lockfile --silent --non-interactive
        yarn lint

    - name: Slack notification FAILED
      uses: Ilshidur/action-slack@2.1.0
      if: failure()
      env:
        SLACK_AVATAR: sender # optional: repository, sender or ImageURL
      with:
        args: "Lint checks *FAILED* for {{GITHUB_REPOSITORY}}*\nYo {{GITHUB_ACTOR}} see why at <{{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/commit/{{GITHUB_SHA}}/checks|action logs>"

    - name: Slack notification SUCCESS
      uses: Ilshidur/action-slack@2.1.0
      if: success()
      with:
        args: "Lint checks *SUCCESSFUL!*\nfrom {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }}"

    - name: Discord notification FAILED
      uses: Ilshidur/action-discord@0.3.0
      if: failure()
      with:
        args: "Lint checks *FAILED* for {{GITHUB_REPOSITORY}}*\nYo {{GITHUB_ACTOR}} see why at <{{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/commit/{{GITHUB_SHA}}/checks|action logs>"

    - name: Discord notification SUCCESS
      uses: Ilshidur/action-discord@0.3.0
      if: success()
      with:
        args: "Lint checks *SUCCESSFUL!*\nfrom {{ GITHUB_ACTOR }} at {{ GITHUB_REPOSITORY }}"
